variable "region"				               {}
variable "env"					               {}
variable "appname"			               {}
variable "bu"					                 {}
variable "az"                          {}


variable "sidekiq_key_name"                    {}
variable "sidekiq_ami"                         {}
variable "sidekiq_count"                       {}
variable "sidekiq_ebs_optimized"               {}
variable "sidekiq_monitoring"                  {}
variable "sidekiq_source_dest_check"           {}
variable "sidekiq_associate_public_ip_address" {}
variable "sidekiq_iam_instance_profile"        {}
variable "sidekiq_root-volume_type"            {}
variable "sidekiq_root-volume_size"            {}
variable "sidekiq_root-volume-delete_on_termination" {}
variable "sidekiq_tag-type"                    {}
variable "sidekiq_tag-cluster"                 {}
variable "sidekiq_tag-vpc"                     {}
variable "sidekiq_tag-name"                    {}
variable "sidekiq_instance_type"               {}
variable "sidekiq_ebs-volume_type"            {}
variable "sidekiq_ebs-volume_size"            {}
variable "sidekiq_ebs-device_name"            {}
variable "sidekiq_ebs-volume-delete_on_termination" {}

variable "yaga_key_name"                    {}
variable "yaga_ami"                         {}
variable "yaga_count"                       {}
variable "yaga_ebs_optimized"               {}
variable "yaga_monitoring"                  {}
variable "yaga_source_dest_check"           {}
variable "yaga_associate_public_ip_address" {}
variable "yaga_iam_instance_profile"        {}
variable "yaga_root-volume_type"            {}
variable "yaga_root-volume_size"            {}
variable "yaga_root-volume-delete_on_termination" {}
variable "yaga_tag-type"                    {}
variable "yaga_tag-cluster"                 {}
variable "yaga_tag-vpc"                     {}
variable "yaga_tag-name"                    {}
variable "yaga_instance_type"               {}

variable "prod_key_name"                    {}
variable "prod_ami"                         {}
variable "prod_count"                       {}
variable "prod_ebs_optimized"               {}
variable "prod_monitoring"                  {}
variable "prod_source_dest_check"           {}
variable "prod_associate_public_ip_address" {}
variable "prod_iam_instance_profile"        {}
variable "prod_root-volume_type"            {}
variable "prod_root-volume_size"            {}
variable "prod_root-volume-delete_on_termination" {}
variable "prod_tag-type"                    {}
variable "prod_tag-cluster"                 {}
variable "prod_tag-vpc"                     {}
variable "prod_tag-name"                    {}
variable "prod_instance_type"               {}
