variable "region"				               {}
variable "env"					               {}
variable "appname"			               {}
variable "bu"					                 {}
variable "key_name"                    {}
variable "az"                          {}
#####################################################
variable "spark_ami"                         {}
variable "spark_count"                       {}
variable "spark_ebs_optimized"               {}
variable "spark_monitoring"                  {}
variable "spark_source_dest_check"           {}
variable "spark_associate_public_ip_address" {}
variable "spark_iam_instance_profile"        {}
variable "spark_root-volume_type"            {}
variable "spark_root-volume_size"            {}
variable "spark_root-volume-delete_on_termination" {}
variable "spark_tag-type"                    {}
variable "spark_tag-cluster"                 {}
variable "spark_tag-vpc"                     {}
variable "spark_tag-name"                    {}
variable "spark_instance_type"               {}
##########################################################
variable "poshmark_ami"                         {}
variable "poshmark_count"                       {}
variable "poshmark_ebs_optimized"               {}
variable "poshmark_monitoring"                  {}
variable "poshmark_source_dest_check"           {}
variable "poshmark_associate_public_ip_address" {}
variable "poshmark_iam_instance_profile"        {}
variable "poshmark_root-volume_type"            {}
variable "poshmark_root-volume_size"            {}
variable "poshmark_root-volume-delete_on_termination" {}
variable "poshmark_tag-type"                    {}
variable "poshmark_tag-cluster"                 {}
variable "poshmark_tag-vpc"                     {}
variable "poshmark_tag-name"                    {}
variable "poshmark_instance_type"               {}
############################################################
variable "poshmark_gateway_ami"                         {}
variable "poshmark_gateway_count"                       {}
variable "poshmark_gateway_ebs_optimized"               {}
variable "poshmark_gateway_monitoring"                  {}
variable "poshmark_gateway_source_dest_check"           {}
variable "poshmark_gateway_associate_public_ip_address" {}
variable "poshmark_gateway_iam_instance_profile"        {}
variable "poshmark_gateway_root-volume_type"            {}
variable "poshmark_gateway_root-volume_size"            {}
variable "poshmark_gateway_root-volume-delete_on_termination" {}
variable "poshmark_gateway_tag-type"                    {}
variable "poshmark_gateway_tag-cluster"                 {}
variable "poshmark_gateway_tag-vpc"                     {}
variable "poshmark_gateway_tag-name"                    {}
variable "poshmark_gateway_instance_type"               {}
