region                      =	"us-west-2"
env                         =	"prod"
appname                     =	"poshmark"
bu                          =	"it"
ami                         = "test_ami"
key_name                    ="test_key"
